[theme]
base = "light"
primaryColor = "#1F77B4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FB"
textColor = "#111111"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "auto"
